services:
  - type: web
    name: ai-excel-analyzer
    runtime: docker
    repo: https://github.com/rebeccaKil/Statistics
    branch: main
    plan: free
    envVars:
      - key: PORT
        value: 8080
      - key: NODE_ENV
        value: production
    healthCheckPath: /health

